server:
  servlet:
    context-path: /RMBTControlServer
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: rtr-backend
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5431/rtr
    username: rtr
    password: password
#    tomcat:
#      test-while-idle: true
#      test-on-borrow: true
#      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  jackson:
    default-property-inclusion: non_null
RMBT_SECRETKEY: RMBT_SECRETKEY

auth0:
  issuer: https://auth.a2332751-f1b8-4d26-8291-dfaef9094f33.netztest.at/
  apiAudience: https://netztest.at
origin: https://testnet2.akostest.net
app:
  rmbt:
    accuracyDetailLimit: 10000
    accuracyButtonLimit: 2000
    duration: 7
    pings: 10
    threads: 6
    version: 0.1.0 || 0.3.0 || ^1.0.0
    language:
      supportedLanguages:
        - de
        - en
        - hr
        - sv
        - pl
        - es
        - is
        - fr
        - nb
        - cs
        - sl
      defaultLanguage: sl
    clientNames:
      - RMBT
      - RMBTjs
      - Open-RMBT
      - RMBTws
      - HW-PROBE
      - RTR-Netztest
      - RMBTel
      - AkosTestNet
      -
application-version:
  host: rtr-api-dev
  server-url: http://localhost:80/RMBTControlServer

elastic-index:
  basicTenantIndexes:
    rtr: basic_test_rtr
  basicQosTenantIndexes:
    rtr: basic_qos_test_rtr
  keepAlive: keep_alive

client-tenant:
  clientTenantMapping:
    rtr: rtr
  defaultTenant: rtr

measurement-server:
  host: http://localhost:8080
  slotWindow: 5
  defaultProviderId: 6

jira:
  requestTypeId: 49
  serviceDeskId: 6
  url: https://specure.atlassian.net
  username: batalin.a@dbbest.com
  password: SuperSecurePassword

---
spring:
  activate:
    on-profile: dev
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URI}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
#    tomcat:
#      test-while-idle: true
#      test-on-borrow: true
#      validation-query: SELECT 1

measurement-server:
  host: api-test.nettest.org

client-tenant:
  clientTenantMapping:
    rtr: rtr_dev
  defaultTenant: rtr

git:
  branch:${git.branch}

application-version:
  host: rtr-api-dev
  server-url: https://rtr-api-dev.nettest.org/RMBTControlServer

---
spring:
  activate:
    on-profile: prod
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${CONTROL_DB_HOST}:${CONTROL_DB_PORT}/${CONTROL_DB_NAME}
    username: ${CONTROL_DB_USER}
    password: ${CONTROL_DB_PASSWORD}
#    tomcat:
#      test-while-idle: true
#      test-on-borrow: true
#      validation-query: SELECT 1

application-version:
  host: ${HOST_ID}
  server-url: ${CONTROL_SERVER_URL}

logging:
    config: ${LOGGING_CONFIG_FILE:classpath:logback.xml}
origin: ${CONTROL_ALLOWED_ORIGIN}
